CREATE BITMAP INDEX FACT_GER_INJURY_BIX ON FACT_GER ( INJURY_ID ) ;

CREATE BITMAP INDEX FACT_GER_DEATH_BIX ON FACT_GER ( DEATH_ID ) ;

CREATE BITMAP INDEX FACT_GER_MER_BIX ON FACT_GER ( MER_ID ) ;

CREATE BITMAP INDEX FACT_GER_RB_BIX ON FACT_GER ( RB_ID ) ;

CREATE BITMAP INDEX FACT_GER_RO_BIX ON FACT_GER ( RO_ID ) ;

CREATE BITMAP INDEX FACT_GER_OTHER_BIX ON FACT_GER ( OTHER_ID ) ; 