-- Schema :  dwtest_monir@bidb


-- Creating Dimension table -- Dim_Cross_Provider

CREATE
  TABLE DIM_CROSS_PROVIDER
  (
    CHILD_PROV_ID  NUMBER ( 10, 0 ) NOT NULL ENABLE,
    PARENT_PROV_ID NUMBER ( 10, 0 ) NOT NULL ENABLE
  )
  NOLOGGING;
        
        
        

-- PROCEDURE FOR INSERTING DATA INTO DIMENSION TABLE FROM SOURCE TABLE 

CREATE OR REPLACE PROCEDURE POPULATE_DIM_CROSS_PROVIDER
AS
BEGIN
  INSERT
  INTO
    DIM_CROSS_PROVIDER
    (
      CHILD_PROV_ID,
      PARENT_PROV_ID
    )
  SELECT
    CHILD_PROV_ID,
    PARENT_PROV_ID
  FROM
    PROD7.CROSS_PROVIDER COMMIT;
END POPULATE_DIM_CROSS_PROVIDER;