-- Schema :  dwtest_monir@bidb

-- Creating Dimension table -- Dimension_Restrain_Behavior

CREATE
  TABLE DIMENSION_RESTRAINT_BEHAVIOR
  (
    RESTRAINT_BEHAVIOR_ID NUMBER ( 10, 0 ) CONSTRAINT RESTRAINT_BEHAVIOR_PK
    PRIMARY KEY,
    END_DATE            TIMESTAMP ( 6 ),
    BEGIN_TIME_HOUR     VARCHAR2 ( 255 BYTE ),
    BEGIN_TIME_MIN      VARCHAR2 ( 255 BYTE ),
    BEGIN_TIME_AM_PM    VARCHAR2 ( 255 BYTE ),
    END_TIME_HOUR       VARCHAR2 ( 255 BYTE ),
    END_TIME_MIN        VARCHAR2 ( 255 BYTE ),
    END_TIME_AM_PM      VARCHAR2 ( 255 BYTE ),
    INJURY_BY_RESTRAINT NUMBER ( 1, 0 ),
    STATUS_EMERGENCY    NUMBER ( 1, 0 )
  )
  NOLOGGING;
  
  
        
-- PROCEDURE FOR INSERTING DATA INTO DIMENSION TABLE FROM SOURCE TABLE 

CREATE OR REPLACE PROCEDURE POPULATE_DIM_RES_BEHAVIOR
AS
BEGIN
  INSERT
  INTO
    DIMENSION_RESTRAINT_BEHAVIOR
    (
      RESTRAINT_BEHAVIOR_ID,
      END_DATE,
      BEGIN_TIME_HOUR,
      BEGIN_TIME_MIN,
      BEGIN_TIME_AM_PM,
      END_TIME_HOUR,
      END_TIME_MIN,
      END_TIME_AM_PM,
      INJURY_BY_RESTRAINT,
      STATUS_EMERGENCY
    )
  SELECT
    ID,
    END_DATE,
    BEGIN_TIME_HOUR,
    BEGIN_TIME_MIN,
    BEGIN_TIME_AM_PM,
    END_TIME_HOUR,
    END_TIME_MIN,
    END_TIME_AM_PM,
    INJURY_BY_RESTRAINT,
    STATUS_EMERGENCY
  FROM
    PROD7.GER_EVENT_RESTRAINT_BEHAVIOR COMMIT;
END POPULATE_DIM_RES_BEHAVIOR;



-- Procedure Execution

EXEC POPULATE_DIM_RES_BEHAVIOR;