-- Schema :  dwtest_monir@bidb

-- Creating Dimension table -- Dimension_Other

CREATE
  TABLE DIMENSION_OTHER
  (
    OTHER_ID          NUMBER ( 10, 0 ) CONSTRAINT OTHER_PK PRIMARY KEY,
    EVENT_OTHER       VARCHAR2 ( 64 BYTE ),
    EVENT_ALTERCATION NUMBER ( 10, 0 ),
    EVENT_ASSAULT     NUMBER ( 10, 0 ),
    EVENT_HOSPITAL    NUMBER ( 10, 0 ),
    EVENT_SUICIDE     NUMBER ( 10, 0 ),
    EVENT_THEFT       NUMBER ( 10, 0 ),
    EVENT_TIME_HOUR   VARCHAR2 ( 2 BYTE ),
    EVENT_TIME_MIN    VARCHAR2 ( 2 BYTE ),
    EVENT_TIME_AM_PM  VARCHAR2 ( 2 BYTE )
  )
  NOLOGGING;
        
-- PROCEDURE FOR INSERTING DATA INTO DIMENSION TABLE FROM SOURCE TABLE 

  CREATE OR REPLACE PROCEDURE POPULATE_DIMENSION_OTHER
  AS
  BEGIN
    INSERT
    INTO
      DIMENSION_OTHER
      (
        OTHER_ID,
        EVENT_OTHER,
        EVENT_ALTERCATION,
        EVENT_ASSAULT,
        EVENT_HOSPITAL,
        EVENT_SUICIDE,
        EVENT_THEFT,
        EVENT_TIME_HOUR,
        EVENT_TIME_MIN,
        EVENT_TIME_AM_PM
      )
    SELECT
      ID,
      EVENT_OTHER,
      EVENT_ALTERCATION,
      EVENT_ASSAULT,
      EVENT_HOSPITAL,
      EVENT_SUICIDE,
      EVENT_THEFT,
      EVENT_TIME_HOUR,
      EVENT_TIME_MIN,
      EVENT_TIME_AM_PM
    FROM
      PROD7.GER_EVENT_OTHER COMMIT;
  END POPULATE_DIMENSION_OTHER;
  

-- Procedure Execution

  EXEC POPULATE_DIMENSION_OTHER;